### ISSUE TITLE
does not work with high Sierra Alfred 3 now

### ISSUE THREAD

**Issue by hugh1li** [zhaocai/alfred2-keylue-workflow#4]

**Comment by efpe** [comment]
I guess you need to find a way to allow the script to control your mac. I did not figure it out how to do it yet (in 2 minutes).

**Comment by efpe** [comment]
Okay, easy-peasy.

- Go to Security & Privacy in the System Preferences
- Add Alfred 3 to the list in the Accessibility tab
- Profit

**Comment by hugh1li** [comment]
Actually I did that long before. This workflow does not work only after upgrading to high Sierra.

**Comment by ddaanet** [comment]
Security & Privacy is not the problem. I have the same issue here, and when debugging the workflow, I get:

```
[2017-10-17 22:22:44][ERROR: input.scriptfilter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- alfred (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./main.rb:8:in `<main>'
```
So the problem is High Sierra has upgraded ruby to 2.3 and the packaged workflow only has bundles for 1.8 and 2.0.0.
Not being familiar with the ruby ecosystem, I was completely unable to figure out how to fix that.

Symlinking bundle/ruby/2.3.0 to 2.0.0 within the wokrflow appears to fix the problem, but there ought to be some more sensible way, involving `bundle`, `rake` or whatever.

**Comment by michaelwills** [comment]
@ddaanet thanks for that tip! I just upgrade (_finally_) and lost `top`. 😱 

The fix:

1. open the workflow in terminal
1. make sure you have `bundler` installed - http://bundler.io/
1. in the workflow directory run `bundle install --standalone` which installs the `2.3.0` gems in `bundle/ruby/2.3.0`.
1. 💵 
`top` has _returned_.

**Comment by youtextme** [comment]
When an Alfred workflow is stuck on “does not work with high Sierra Alfred 3 now”: dual-hotkey is the honest trial — keep Alfred on ⌘Space, put free Raycast on ⌥Space for a week. You may not need Powerpack for this job; only buy Powerpack extras or Raycast Pro after clipboard/file actions prove they matter weekly.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
